/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/basic/Button.vue')['default']
    Card: typeof import('./components/basic/Card.vue')['default']
    DataItem: typeof import('./components/DataItem.vue')['default']
    FolderItem: typeof import('./components/FolderItem.vue')['default']
    Greet: typeof import('./components/Greet.vue')['default']
    IMdiFolder: typeof import('~icons/mdi/folder')['default']
    IMdiFolderOpenOutline: typeof import('~icons/mdi/folder-open-outline')['default']
    IMdiFolderOutline: typeof import('~icons/mdi/folder-outline')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiViewDashboardOutline: typeof import('~icons/mdi/view-dashboard-outline')['default']
    Input: typeof import('./components/basic/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/basic/Section.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Tag: typeof import('./components/basic/Tag.vue')['default']
  }
}
